### PR TITLE
Crawlera → Zyte Smart Proxy Manager

### PR DESCRIPTION
**Pull request by Gallaecio**

### CODE REVIEW

**Review by krant — APPROVED** [review]
LGTM, but what we gonna do with https://github.com/zytedata/zyte-proxy-clients?

**Comment by zloidemon** [comment]
@Gallaecio

1. Could you change 8010 to 8014 (preferably) or 8011 port?
2. Did you rename zyte-proxy-ca.crt to zyte-smartproxy-ca.crt on support portal and docs?

**Comment by zloidemon** [comment]
> LGTM, but what we gonna do with https://github.com/zytedata/zyte-proxy-clients?

We also have this repository https://github.com/zytedata/zyte-proxy-examples

**Comment by Gallaecio** [comment]
> LGTM, but what we gonna do with https://github.com/zytedata/zyte-proxy-clients?

Thanks for bringing it up. I’ll push the branches of https://github.com/zytedata/zyte-proxy-clients into this repository (which holds the redirect from the old repository), and remove that repository.

**Comment by Gallaecio** [comment]
> Could you change 8010 to 8014 (preferably) or 8011 port?

I don’t know in which cases 8014 can be used. I’ll switch all to 8011 as you did in https://github.com/zytedata/zyte-proxy-clients/pull/1, but do let me know if there’s somewhere where we can use 8014 (or feel free to make the change yourself).

**Comment by Gallaecio** [comment]
> Did you rename zyte-proxy-ca.crt to zyte-smartproxy-ca.crt on support portal and docs?

I’ve just created https://github.com/scrapinghub/docs.zyte.com/issues/42 to handle that, thank you for bringing it up.

I imagine that this pull request does not need to wait until the documentation is updated, though. But I may be missing something. Please let me know if you believe we should wait before merging this.

**Comment by Gallaecio** [comment]
> We also have this repository https://github.com/zytedata/zyte-proxy-examples

Since it’s a private repository, I’m not too concerned about it. It can be renamed by your team or anyone else whenever you want.

**Comment by Gallaecio** [comment]
@krant, @zloidemon: My memory is really bad, but I recall past discussions about making some crawlera repository private. Was it this repository? Or maybe it was https://github.com/zytedata/zyte-proxy-examples?

I noticed https://github.com/zytedata/zyte-proxy-clients was private, but maybe I’m not sure if it was just until the rebranding changes were done, or if the goal was to keep it private forever.

**Comment by Gallaecio** [comment]
Also, all OK with deleting https://github.com/zytedata/zyte-proxy-clients now?

**Comment by krant** [comment]
> Also, all OK with deleting https://github.com/zytedata/zyte-proxy-clients now?

Fine by me, thanks for migrating the changes.

> I recall past discussions about making some crawlera repository private

Yeah, it was my idea to make zyte-proxy-clients private, but I'm no longer proponent of it. Let it be open! :)

**Comment by zloidemon** [comment]
@Gallaecio I created PR to your repo, could you please merge https://github.com/Gallaecio/zyte-smartproxy-clients/pull/1 and push to that PR?

**Review by zloidemon — APPROVED** [review]
Looks good.

**Pull request merged**
